/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SQL Trading API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customFetch } from "../../fetcher";

/**
 * 대시보드 HTML 반환
 * @summary Index
 */
export type indexGetResponse200 = {
  data: unknown;
  status: 200;
};

export type indexGetResponseSuccess = indexGetResponse200 & {
  headers: Headers;
};
export type indexGetResponse = indexGetResponseSuccess;

export const getIndexGetUrl = () => {
  return `/`;
};

export const indexGet = async (
  options?: RequestInit,
): Promise<indexGetResponse> => {
  return customFetch<indexGetResponse>(getIndexGetUrl(), {
    ...options,
    method: "GET",
  });
};

export const getIndexGetQueryKey = () => {
  return [`/`] as const;
};

export const getIndexGetQueryOptions = <
  TData = Awaited<ReturnType<typeof indexGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof indexGet>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getIndexGetQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof indexGet>>> = ({
    signal,
  }) => indexGet({ signal });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof indexGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type IndexGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof indexGet>>
>;
export type IndexGetQueryError = unknown;

export function useIndexGet<
  TData = Awaited<ReturnType<typeof indexGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof indexGet>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof indexGet>>,
          TError,
          Awaited<ReturnType<typeof indexGet>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useIndexGet<
  TData = Awaited<ReturnType<typeof indexGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof indexGet>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof indexGet>>,
          TError,
          Awaited<ReturnType<typeof indexGet>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useIndexGet<
  TData = Awaited<ReturnType<typeof indexGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof indexGet>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Index
 */

export function useIndexGet<
  TData = Awaited<ReturnType<typeof indexGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof indexGet>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getIndexGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 섹터별 현황
 * @summary Get Sectors
 */
export type getSectorsApiSectorsGetResponse200 = {
  data: unknown;
  status: 200;
};

export type getSectorsApiSectorsGetResponseSuccess =
  getSectorsApiSectorsGetResponse200 & {
    headers: Headers;
  };
export type getSectorsApiSectorsGetResponse =
  getSectorsApiSectorsGetResponseSuccess;

export const getGetSectorsApiSectorsGetUrl = () => {
  return `/api/sectors`;
};

export const getSectorsApiSectorsGet = async (
  options?: RequestInit,
): Promise<getSectorsApiSectorsGetResponse> => {
  return customFetch<getSectorsApiSectorsGetResponse>(
    getGetSectorsApiSectorsGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetSectorsApiSectorsGetQueryKey = () => {
  return [`/api/sectors`] as const;
};

export const getGetSectorsApiSectorsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getSectorsApiSectorsGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getSectorsApiSectorsGet>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetSectorsApiSectorsGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSectorsApiSectorsGet>>
  > = ({ signal }) => getSectorsApiSectorsGet({ signal });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSectorsApiSectorsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetSectorsApiSectorsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSectorsApiSectorsGet>>
>;
export type GetSectorsApiSectorsGetQueryError = unknown;

export function useGetSectorsApiSectorsGet<
  TData = Awaited<ReturnType<typeof getSectorsApiSectorsGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSectorsApiSectorsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSectorsApiSectorsGet>>,
          TError,
          Awaited<ReturnType<typeof getSectorsApiSectorsGet>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetSectorsApiSectorsGet<
  TData = Awaited<ReturnType<typeof getSectorsApiSectorsGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSectorsApiSectorsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSectorsApiSectorsGet>>,
          TError,
          Awaited<ReturnType<typeof getSectorsApiSectorsGet>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetSectorsApiSectorsGet<
  TData = Awaited<ReturnType<typeof getSectorsApiSectorsGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSectorsApiSectorsGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get Sectors
 */

export function useGetSectorsApiSectorsGet<
  TData = Awaited<ReturnType<typeof getSectorsApiSectorsGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSectorsApiSectorsGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetSectorsApiSectorsGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 트레이딩 신호
 * @summary Get Signals
 */
export type getSignalsApiSignalsGetResponse200 = {
  data: unknown;
  status: 200;
};

export type getSignalsApiSignalsGetResponseSuccess =
  getSignalsApiSignalsGetResponse200 & {
    headers: Headers;
  };
export type getSignalsApiSignalsGetResponse =
  getSignalsApiSignalsGetResponseSuccess;

export const getGetSignalsApiSignalsGetUrl = () => {
  return `/api/signals`;
};

export const getSignalsApiSignalsGet = async (
  options?: RequestInit,
): Promise<getSignalsApiSignalsGetResponse> => {
  return customFetch<getSignalsApiSignalsGetResponse>(
    getGetSignalsApiSignalsGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetSignalsApiSignalsGetQueryKey = () => {
  return [`/api/signals`] as const;
};

export const getGetSignalsApiSignalsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getSignalsApiSignalsGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getSignalsApiSignalsGet>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetSignalsApiSignalsGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSignalsApiSignalsGet>>
  > = ({ signal }) => getSignalsApiSignalsGet({ signal });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSignalsApiSignalsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetSignalsApiSignalsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSignalsApiSignalsGet>>
>;
export type GetSignalsApiSignalsGetQueryError = unknown;

export function useGetSignalsApiSignalsGet<
  TData = Awaited<ReturnType<typeof getSignalsApiSignalsGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSignalsApiSignalsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSignalsApiSignalsGet>>,
          TError,
          Awaited<ReturnType<typeof getSignalsApiSignalsGet>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetSignalsApiSignalsGet<
  TData = Awaited<ReturnType<typeof getSignalsApiSignalsGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSignalsApiSignalsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSignalsApiSignalsGet>>,
          TError,
          Awaited<ReturnType<typeof getSignalsApiSignalsGet>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetSignalsApiSignalsGet<
  TData = Awaited<ReturnType<typeof getSignalsApiSignalsGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSignalsApiSignalsGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get Signals
 */

export function useGetSignalsApiSignalsGet<
  TData = Awaited<ReturnType<typeof getSignalsApiSignalsGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSignalsApiSignalsGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetSignalsApiSignalsGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 종목 현황
 * @summary Get Stocks
 */
export type getStocksApiStocksGetResponse200 = {
  data: unknown;
  status: 200;
};

export type getStocksApiStocksGetResponseSuccess =
  getStocksApiStocksGetResponse200 & {
    headers: Headers;
  };
export type getStocksApiStocksGetResponse =
  getStocksApiStocksGetResponseSuccess;

export const getGetStocksApiStocksGetUrl = () => {
  return `/api/stocks`;
};

export const getStocksApiStocksGet = async (
  options?: RequestInit,
): Promise<getStocksApiStocksGetResponse> => {
  return customFetch<getStocksApiStocksGetResponse>(
    getGetStocksApiStocksGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetStocksApiStocksGetQueryKey = () => {
  return [`/api/stocks`] as const;
};

export const getGetStocksApiStocksGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getStocksApiStocksGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getStocksApiStocksGet>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetStocksApiStocksGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getStocksApiStocksGet>>
  > = ({ signal }) => getStocksApiStocksGet({ signal });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getStocksApiStocksGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetStocksApiStocksGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStocksApiStocksGet>>
>;
export type GetStocksApiStocksGetQueryError = unknown;

export function useGetStocksApiStocksGet<
  TData = Awaited<ReturnType<typeof getStocksApiStocksGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStocksApiStocksGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStocksApiStocksGet>>,
          TError,
          Awaited<ReturnType<typeof getStocksApiStocksGet>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetStocksApiStocksGet<
  TData = Awaited<ReturnType<typeof getStocksApiStocksGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStocksApiStocksGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStocksApiStocksGet>>,
          TError,
          Awaited<ReturnType<typeof getStocksApiStocksGet>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetStocksApiStocksGet<
  TData = Awaited<ReturnType<typeof getStocksApiStocksGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStocksApiStocksGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get Stocks
 */

export function useGetStocksApiStocksGet<
  TData = Awaited<ReturnType<typeof getStocksApiStocksGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStocksApiStocksGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetStocksApiStocksGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 운임 지수
 * @summary Get Freight
 */
export type getFreightApiFreightGetResponse200 = {
  data: unknown;
  status: 200;
};

export type getFreightApiFreightGetResponseSuccess =
  getFreightApiFreightGetResponse200 & {
    headers: Headers;
  };
export type getFreightApiFreightGetResponse =
  getFreightApiFreightGetResponseSuccess;

export const getGetFreightApiFreightGetUrl = () => {
  return `/api/freight`;
};

export const getFreightApiFreightGet = async (
  options?: RequestInit,
): Promise<getFreightApiFreightGetResponse> => {
  return customFetch<getFreightApiFreightGetResponse>(
    getGetFreightApiFreightGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetFreightApiFreightGetQueryKey = () => {
  return [`/api/freight`] as const;
};

export const getGetFreightApiFreightGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getFreightApiFreightGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getFreightApiFreightGet>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetFreightApiFreightGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFreightApiFreightGet>>
  > = ({ signal }) => getFreightApiFreightGet({ signal });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFreightApiFreightGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetFreightApiFreightGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFreightApiFreightGet>>
>;
export type GetFreightApiFreightGetQueryError = unknown;

export function useGetFreightApiFreightGet<
  TData = Awaited<ReturnType<typeof getFreightApiFreightGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFreightApiFreightGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFreightApiFreightGet>>,
          TError,
          Awaited<ReturnType<typeof getFreightApiFreightGet>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetFreightApiFreightGet<
  TData = Awaited<ReturnType<typeof getFreightApiFreightGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFreightApiFreightGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFreightApiFreightGet>>,
          TError,
          Awaited<ReturnType<typeof getFreightApiFreightGet>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetFreightApiFreightGet<
  TData = Awaited<ReturnType<typeof getFreightApiFreightGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFreightApiFreightGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get Freight
 */

export function useGetFreightApiFreightGet<
  TData = Awaited<ReturnType<typeof getFreightApiFreightGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFreightApiFreightGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetFreightApiFreightGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 전체 요약
 * @summary Get Summary
 */
export type getSummaryApiSummaryGetResponse200 = {
  data: unknown;
  status: 200;
};

export type getSummaryApiSummaryGetResponseSuccess =
  getSummaryApiSummaryGetResponse200 & {
    headers: Headers;
  };
export type getSummaryApiSummaryGetResponse =
  getSummaryApiSummaryGetResponseSuccess;

export const getGetSummaryApiSummaryGetUrl = () => {
  return `/api/summary`;
};

export const getSummaryApiSummaryGet = async (
  options?: RequestInit,
): Promise<getSummaryApiSummaryGetResponse> => {
  return customFetch<getSummaryApiSummaryGetResponse>(
    getGetSummaryApiSummaryGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetSummaryApiSummaryGetQueryKey = () => {
  return [`/api/summary`] as const;
};

export const getGetSummaryApiSummaryGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getSummaryApiSummaryGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getSummaryApiSummaryGet>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetSummaryApiSummaryGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSummaryApiSummaryGet>>
  > = ({ signal }) => getSummaryApiSummaryGet({ signal });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSummaryApiSummaryGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetSummaryApiSummaryGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSummaryApiSummaryGet>>
>;
export type GetSummaryApiSummaryGetQueryError = unknown;

export function useGetSummaryApiSummaryGet<
  TData = Awaited<ReturnType<typeof getSummaryApiSummaryGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSummaryApiSummaryGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSummaryApiSummaryGet>>,
          TError,
          Awaited<ReturnType<typeof getSummaryApiSummaryGet>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetSummaryApiSummaryGet<
  TData = Awaited<ReturnType<typeof getSummaryApiSummaryGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSummaryApiSummaryGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSummaryApiSummaryGet>>,
          TError,
          Awaited<ReturnType<typeof getSummaryApiSummaryGet>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetSummaryApiSummaryGet<
  TData = Awaited<ReturnType<typeof getSummaryApiSummaryGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSummaryApiSummaryGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get Summary
 */

export function useGetSummaryApiSummaryGet<
  TData = Awaited<ReturnType<typeof getSummaryApiSummaryGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSummaryApiSummaryGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetSummaryApiSummaryGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 경제지표
 * @summary Get Indicators
 */
export type getIndicatorsApiIndicatorsGetResponse200 = {
  data: unknown;
  status: 200;
};

export type getIndicatorsApiIndicatorsGetResponseSuccess =
  getIndicatorsApiIndicatorsGetResponse200 & {
    headers: Headers;
  };
export type getIndicatorsApiIndicatorsGetResponse =
  getIndicatorsApiIndicatorsGetResponseSuccess;

export const getGetIndicatorsApiIndicatorsGetUrl = () => {
  return `/api/indicators`;
};

export const getIndicatorsApiIndicatorsGet = async (
  options?: RequestInit,
): Promise<getIndicatorsApiIndicatorsGetResponse> => {
  return customFetch<getIndicatorsApiIndicatorsGetResponse>(
    getGetIndicatorsApiIndicatorsGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetIndicatorsApiIndicatorsGetQueryKey = () => {
  return [`/api/indicators`] as const;
};

export const getGetIndicatorsApiIndicatorsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getIndicatorsApiIndicatorsGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getIndicatorsApiIndicatorsGet>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetIndicatorsApiIndicatorsGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getIndicatorsApiIndicatorsGet>>
  > = ({ signal }) => getIndicatorsApiIndicatorsGet({ signal });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getIndicatorsApiIndicatorsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetIndicatorsApiIndicatorsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getIndicatorsApiIndicatorsGet>>
>;
export type GetIndicatorsApiIndicatorsGetQueryError = unknown;

export function useGetIndicatorsApiIndicatorsGet<
  TData = Awaited<ReturnType<typeof getIndicatorsApiIndicatorsGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIndicatorsApiIndicatorsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIndicatorsApiIndicatorsGet>>,
          TError,
          Awaited<ReturnType<typeof getIndicatorsApiIndicatorsGet>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetIndicatorsApiIndicatorsGet<
  TData = Awaited<ReturnType<typeof getIndicatorsApiIndicatorsGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIndicatorsApiIndicatorsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIndicatorsApiIndicatorsGet>>,
          TError,
          Awaited<ReturnType<typeof getIndicatorsApiIndicatorsGet>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetIndicatorsApiIndicatorsGet<
  TData = Awaited<ReturnType<typeof getIndicatorsApiIndicatorsGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIndicatorsApiIndicatorsGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get Indicators
 */

export function useGetIndicatorsApiIndicatorsGet<
  TData = Awaited<ReturnType<typeof getIndicatorsApiIndicatorsGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIndicatorsApiIndicatorsGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetIndicatorsApiIndicatorsGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 물류 추적 데이터
 * @summary Get Logistics
 */
export type getLogisticsApiLogisticsGetResponse200 = {
  data: unknown;
  status: 200;
};

export type getLogisticsApiLogisticsGetResponseSuccess =
  getLogisticsApiLogisticsGetResponse200 & {
    headers: Headers;
  };
export type getLogisticsApiLogisticsGetResponse =
  getLogisticsApiLogisticsGetResponseSuccess;

export const getGetLogisticsApiLogisticsGetUrl = () => {
  return `/api/logistics`;
};

export const getLogisticsApiLogisticsGet = async (
  options?: RequestInit,
): Promise<getLogisticsApiLogisticsGetResponse> => {
  return customFetch<getLogisticsApiLogisticsGetResponse>(
    getGetLogisticsApiLogisticsGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetLogisticsApiLogisticsGetQueryKey = () => {
  return [`/api/logistics`] as const;
};

export const getGetLogisticsApiLogisticsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getLogisticsApiLogisticsGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getLogisticsApiLogisticsGet>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetLogisticsApiLogisticsGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getLogisticsApiLogisticsGet>>
  > = ({ signal }) => getLogisticsApiLogisticsGet({ signal });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getLogisticsApiLogisticsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetLogisticsApiLogisticsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLogisticsApiLogisticsGet>>
>;
export type GetLogisticsApiLogisticsGetQueryError = unknown;

export function useGetLogisticsApiLogisticsGet<
  TData = Awaited<ReturnType<typeof getLogisticsApiLogisticsGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLogisticsApiLogisticsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLogisticsApiLogisticsGet>>,
          TError,
          Awaited<ReturnType<typeof getLogisticsApiLogisticsGet>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetLogisticsApiLogisticsGet<
  TData = Awaited<ReturnType<typeof getLogisticsApiLogisticsGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLogisticsApiLogisticsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLogisticsApiLogisticsGet>>,
          TError,
          Awaited<ReturnType<typeof getLogisticsApiLogisticsGet>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetLogisticsApiLogisticsGet<
  TData = Awaited<ReturnType<typeof getLogisticsApiLogisticsGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLogisticsApiLogisticsGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get Logistics
 */

export function useGetLogisticsApiLogisticsGet<
  TData = Awaited<ReturnType<typeof getLogisticsApiLogisticsGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLogisticsApiLogisticsGet>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetLogisticsApiLogisticsGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}
